name=TB6612FNG_pse
version=1.0.0
author=JeromeTOMSKI
maintainer=JeromeTOMSKI
sentence=Librairie simple et en français, permettant de piloter un TB6612FNG
paragraph=Librairie PassionElectronique.fr (pse), compatible Arduino AVR et ESP32
category=Device Control
url=https://github.com/PassionElectronique/TB6612FNG_pse_Arduino_Library
architectures=avr,esp32